# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7bafa891cc8b8c9d8ca6b76882a6f56ddf141ef4990e1fcfa9105c7917e180e56efbf8a1374d281e9b4eccb8bae8f27c3a98b9238a699c3808d7ce215027b3d

test:
  secret_key_base: 9b481e9d16393d43ee853582c6a0e6d28b735d3f5c0c55d77546333ea7dfd5067543c4eca00ca0d24fa8aed744f709e174fa2755a2867c7d84b47ad7814bb0f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
